Feature/sheet task
vc-bhanudatsinh/nodejstask pull request #5
Opened 2023-05-17 09:16 UTC by vc-bhanudatsinh

intial code push of sheet-task

2023-05-24 13:50 UTC, vc-mohit commented on SheetTask/src/controllers/sheetController.js
remove consoles

2023-05-24 13:59 UTC, vc-mohit commented on SheetTask/src/controllers/sheetController.js
variables names should be as per the functionality

2023-05-24 14:00 UTC, vc-mohit requested changes
Add code commenting which defines the functionality

2023-05-25 06:05 UTC, vc-bhanudatsinh commented
@vc-mohit I have made changes in the [#db87f9b](https://github.com/vc-bhanudatsinh/nodejstask/pull/5/commits/db87f9b9780af7e2cbe9dcb8297a38ffa7a9b29c) commit.

2023-05-25 12:13 UTC, vc-mohit approved these changes

2023-05-25 12:14 UTC, merged